// src/components/ColorRamp.tsx
import * as React from 'react'
import * as scales from 'd3-scale-chromatic'
import { rgb } from 'd3-color'

interface Props extends React.ComponentPropsWithoutRef<any> {
  interpolator: string
  width: number
  height: number
}

const ColorRamp = ({ width, height, interpolator, ...props }: Props) => {
  const canvasRef = React.useRef(null)
  const interpolate = scales[interpolator]
  const n = 256
  const colors = []

  props.className = `palette ${props.className}`

  for (let i = 0; i < n; ++i) {
    colors.push(rgb(interpolate(i / (n - 1))).hex())
  }

  React.useEffect(() => {
    const ctx = canvasRef.current.getContext('2d')
    for (let i = 0; i < n; ++i) {
      ctx.fillStyle = colors[i]
      ctx.fillRect(i, 0, 1, 1)
    }
  })

  return (
    <canvas
      ref={canvasRef}
      width={256}
      height={1}
      style={{ height: `${height}px`, width: `${width}px` }}
      {...props}
    />
  )
}

export default ColorRamp

// src/components/ColorRamp.svelte
<script>
  import { onMount } from 'svelte'
  import { colorsFromInterpolator } from '../utilities'

  export let interpolator = 'interpolateRainbow'
  export let width = 256
  export let height = 6

  let canvas
  let steps = 256

  onMount(() => {
    const ctx = canvas.getContext('2d')
    const colors = colorsFromInterpolator({ steps, interpolator })
    for (let i = 0; i < steps; ++i) {
      ctx.fillStyle = colors[i].hex
      ctx.fillRect(i, 0, 1, 1)
    }
  })
</script>

<canvas
  bind:this={canvas}
  on:click
  width={256}
  height={1}
  style={`width: ${width}px; height: ${height}px`} />

<style>
  canvas {
    margin: 0;
    padding: 0;
  }
</style>
